name: daraz_clone_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.1
  shared_preferences: ^2.0.18
  get_storage: ^2.1.1
  flutter_svg: ^1.1.6
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.3
  dio: ^5.1.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets the application
  assets:
    - assets/images/
    - assets/icons/

  # To add fonts 
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Helvetica
      fonts: 
        - asset:  assets/fonts/Helvetica.ttf
    - family: Helvetica Neue 
      fonts: 
        - asset:  assets/fonts/Helvetica-Neue-Regular.otf
  